### ISSUE TITLE
Magic

### ISSUE THREAD

**Issue by iooab10** [MicrosoftDocs/ai-builder#69] opened 2022-08-16 15:32 UTC
[Enter feedback here]

Can you explain the magic behind the append to string as I have no option for text and value and what is hidden under whateer you pasted into the picture????  Very confusing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dbf2f03-de23-1930-3121-f873904d435b
* Version Independent ID: 35979f8f-c655-c842-b0a5-a9750b48101e
* Content: [Use entity extraction model in Power Automate - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prebuilt-entity-extraction-pwr-automate)
* Content Source: [ai-builder-docs/prebuilt-entity-extraction-pwr-automate.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prebuilt-entity-extraction-pwr-automate.md)
* Service: **aibuilder**
* GitHub Login: @mfotedar
* Microsoft Alias: **mfotedar**

**Comment by v-aangie** [comment] 2022-08-30 20:26
@iooab10 - Thanks for your feedback. This is a duplicate of https://github.com/MicrosoftDocs/ai-builder/issues/70. Closing this issue.

**Closed by v-aangie** 2022-08-30 20:26 UTC
